### ISSUE TITLE
WriteAPI error with flux-enabled=true while using influxdb 1.8.1, but QueryAPI NOT

### ISSUE THREAD

**Issue by yijia2413** [influxdata/influxdb-client-go#164]
##  Steps to reproduce
I use influxdb in docker, the following are `docker-compose.yml` and `influxdb.conf`

### influxdb.conf
```
[meta]
  dir = "/var/lib/influxdb/meta"

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
[http]
  flux-enabled = true
```

### docker-compose.yml
```
version: '3.5'
services:
  influxdb:
    image: influxdb:1.8.1-alpine
    ports:
      - "8086:8086"
    restart: always
    environment:
      INFLUXDB_DB: prometheus 
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: root
    healthcheck:
      test: " wget --server-response --spider --quiet http://localhost:8086/ping"
      interval: 3s
      timeout: 10s
      retries: 10
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/influxdb.conf:/etc/influxdb/influxdb.conf
```

### start influxdb
`influxdb.conf` put in `/root` dir, then run `docker-compose up -d`

### golang code
```go
package main

import (
	"context"
	"fmt"
	"time"

	influxdb2 "github.com/influxdata/influxdb-client-go"
)

func main() {
	userName := "root"
	password := "root"
	// Create a client
	// Supply a string in the form: "username:password" as a token. Set empty value for an unauthenticated server
	client := influxdb2.NewClient("http://xxx.xxx.xxx.xxx:8086", fmt.Sprintf("%s:%s", userName, password))
	// Get the blocking write client
	// Supply a string in the form database/retention-policy as a bucket. Skip retention policy for the default one, use just a database name (without the slash character)
	// Org name is not used
	writeAPI := client.WriteApiBlocking("", "prometheus/autogen")
	// create point using full params constructor
	p := influxdb2.NewPoint("stat",
		map[string]string{"unit": "temperature"},
		map[string]interface{}{"avg": 24.5, "max": 45},
		time.Now())
	// Write data
	err := writeAPI.WritePoint(context.Background(), p)
	if err != nil {
		fmt.Printf("Write error: %s\n", err.Error())
	}
	// Close client
	client.Close()
}
```

then I run `go run test.go`, **Errors** come!

But when I use QueryApi as the example shows, it looks good.

### Expected behavior
no error occur, print nothing

### Actual behavior
console print 

```
2020/07/28 16:32:03 [E]! Write error: : 
Write error: :
```

### Specifications
 - Go Version: go version go1.14.4 linux/amd64
 - InfluxDB Version: 1.8.1, the docker tag is `influxdb:1.8.1-alpine`
 - Platform: CentOS Linux release 7.4.1708 (Core)
-  Docker version: 18.09.5
- Docker compose version: docker-compose version 1.24.0, build 0aa59064
